version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./data:/app/data
      - ./temp:/app/temp
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
      - DATABASE_PATH=/app/data/reminders.db
    restart: always
