version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./reminders.db:/app/reminders.db
      - ./temp:/app/temp
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
    restart: always
